export const LANGUAGES = [
    {"id":"ab","itemName":"Abkhaz","nativeName":"аҧсуа"},
    {"id":"aa","itemName":"Afar","nativeName":"Afaraf"},
    {"id":"af","itemName":"Afrikaans","nativeName":"Afrikaans"},
    {"id":"ak","itemName":"Akan","nativeName":"Akan"},
    {"id":"sq","itemName":"Albanian","nativeName":"Shqip"},
    {"id":"am","itemName":"Amharic","nativeName":"አማርኛ"},
    {"id":"ar","itemName":"Arabic","nativeName":"العربية"},
    {"id":"an","itemName":"Aragonese","nativeName":"Aragonés"},
    {"id":"hy","itemName":"Armenian","nativeName":"Հայերեն"},
    {"id":"as","itemName":"Assamese","nativeName":"অসমীয়া"},
    {"id":"av","itemName":"Avaric","nativeName":"авар мацӀ, магӀарул мацӀ"},
    {"id":"ae","itemName":"Avestan","nativeName":"avesta"},
    {"id":"ay","itemName":"Aymara","nativeName":"aymar aru"},
    {"id":"az","itemName":"Azerbaijani","nativeName":"azərbaycan dili"},
    {"id":"bm","itemName":"Bambara","nativeName":"bamanankan"},
    {"id":"ba","itemName":"Bashkir","nativeName":"башҡорт теле"},
    {"id":"eu","itemName":"Basque","nativeName":"euskara, euskera"},
    {"id":"be","itemName":"Belarusian","nativeName":"Беларуская"},
    {"id":"bn","itemName":"Bengali","nativeName":"বাংলা"},
    {"id":"bh","itemName":"Bihari","nativeName":"भोजपुरी"},
    {"id":"bi","itemName":"Bislama","nativeName":"Bislama"},
    {"id":"bs","itemName":"Bosnian","nativeName":"bosanski jezik"},
    {"id":"br","itemName":"Breton","nativeName":"brezhoneg"},
    {"id":"bg","itemName":"Bulgarian","nativeName":"български език"},
    {"id":"my","itemName":"Burmese","nativeName":"ဗမာစာ"},
    {"id":"ca","itemName":"Catalan; Valencian","nativeName":"Català"},
    {"id":"ch","itemName":"Chamorro","nativeName":"Chamoru"},
    {"id":"ce","itemName":"Chechen","nativeName":"нохчийн мотт"},
    {"id":"ny","itemName":"Chichewa; Chewa; Nyanja","nativeName":"chiCheŵa, chinyanja"},
    {"id":"zh","itemName":"Chinese","nativeName":"中文 (Zhōngwén), 汉语, 漢語"},
    {"id":"cv","itemName":"Chuvash","nativeName":"чӑваш чӗлхи"},
    {"id":"kw","itemName":"Cornish","nativeName":"Kernewek"},
    {"id":"co","itemName":"Corsican","nativeName":"corsu, lingua corsa"},
    {"id":"cr","itemName":"Cree","nativeName":"ᓀᐦᐃᔭᐍᐏᐣ"},
    {"id":"hr","itemName":"Croatian","nativeName":"hrvatski"},
    {"id":"cs","itemName":"Czech","nativeName":"česky, čeština"},
    {"id":"da","itemName":"Danish","nativeName":"dansk"},
    {"id":"dv","itemName":"Divehi; Dhivehi; Maldivian;","nativeName":"ދިވެހި"},
    {"id":"nl","itemName":"Dutch","nativeName":"Nederlands, Vlaams"},
    {"id":"en","itemName":"English","nativeName":"English"},
    {"id":"eo","itemName":"Esperanto","nativeName":"Esperanto"},
    {"id":"et","itemName":"Estonian","nativeName":"eesti, eesti keel"},
    {"id":"ee","itemName":"Ewe","nativeName":"Eʋegbe"},
    {"id":"fo","itemName":"Faroese","nativeName":"føroyskt"},
    {"id":"fj","itemName":"Fijian","nativeName":"vosa Vakaviti"},
    {"id":"fi","itemName":"Finnish","nativeName":"suomi, suomen kieli"},
    {"id":"fr","itemName":"French","nativeName":"français, langue française"},
    {"id":"ff","itemName":"Fula; Fulah; Pulaar; Pular","nativeName":"Fulfulde, Pulaar, Pular"},
    {"id":"gl","itemName":"Galician","nativeName":"Galego"},
    {"id":"ka","itemName":"Georgian","nativeName":"ქართული"},
    {"id":"de","itemName":"German","nativeName":"Deutsch"},
    {"id":"el","itemName":"Greek, Modern","nativeName":"Ελληνικά"},
    {"id":"gn","itemName":"Guaraní","nativeName":"Avañeẽ"},
    {"id":"gu","itemName":"Gujarati","nativeName":"ગુજરાતી"},
    {"id":"ht","itemName":"Haitian; Haitian Creole","nativeName":"Kreyòl ayisyen"},
    {"id":"ha","itemName":"Hausa","nativeName":"Hausa, هَوُسَ"},
    {"id":"he","itemName":"Hebrew (modern)","nativeName":"עברית"},
    {"id":"hz","itemName":"Herero","nativeName":"Otjiherero"},
    {"id":"hi","itemName":"Hindi","nativeName":"हिन्दी, हिंदी"},
    {"id":"ho","itemName":"Hiri Motu","nativeName":"Hiri Motu"},
    {"id":"hu","itemName":"Hungarian","nativeName":"Magyar"},
    {"id":"ia","itemName":"Interlingua","nativeName":"Interlingua"},
    {"id":"id","itemName":"Indonesian","nativeName":"Bahasa Indonesia"},
    {"id":"ie","itemName":"Interlingue","nativeName":"Originally called Occidental; then Interlingue after WWII"},
    {"id":"ga","itemName":"Irish","nativeName":"Gaeilge"},
    {"id":"ig","itemName":"Igbo","nativeName":"Asụsụ Igbo"},
    {"id":"ik","itemName":"Inupiaq","nativeName":"Iñupiaq, Iñupiatun"},
    {"id":"io","itemName":"Ido","nativeName":"Ido"},
    {"id":"is","itemName":"Icelandic","nativeName":"Íslenska"},
    {"id":"it","itemName":"Italian","nativeName":"Italiano"},
    {"id":"iu","itemName":"Inuktitut","nativeName":"ᐃᓄᒃᑎᑐᑦ"},
    {"id":"ja","itemName":"Japanese","nativeName":"日本語 (にほんご／にっぽんご)"},
    {"id":"jv","itemName":"Javanese","nativeName":"basa Jawa"},
    {"id":"kl","itemName":"Kalaallisut, Greenlandic","nativeName":"kalaallisut, kalaallit oqaasii"},
    {"id":"kn","itemName":"Kannada","nativeName":"ಕನ್ನಡ"},
    {"id":"kr","itemName":"Kanuri","nativeName":"Kanuri"},
    {"id":"ks","itemName":"Kashmiri","nativeName":"कश्मीरी, كشميري‎"},
    {"id":"kk","itemName":"Kazakh","nativeName":"Қазақ тілі"},
    {"id":"km","itemName":"Khmer","nativeName":"ភាសាខ្មែរ"},
    {"id":"ki","itemName":"Kikuyu, Gikuyu","nativeName":"Gĩkũyũ"},
    {"id":"rw","itemName":"Kinyarwanda","nativeName":"Ikinyarwanda"},
    {"id":"ky","itemName":"Kirghiz, Kyrgyz","nativeName":"кыргыз тили"},
    {"id":"kv","itemName":"Komi","nativeName":"коми кыв"},
    {"id":"kg","itemName":"Kongo","nativeName":"KiKongo"},
    {"id":"ko","itemName":"Korean","nativeName":"한국어 (韓國語), 조선말 (朝鮮語)"},
    {"id":"ku","itemName":"Kurdish","nativeName":"Kurdî, كوردی‎"},
    {"id":"kj","itemName":"Kwanyama, Kuanyama","nativeName":"Kuanyama"},
    {"id":"la","itemName":"Latin","nativeName":"latine, lingua latina"},
    {"id":"lb","itemName":"Luxembourgish, Letzeburgesch","nativeName":"Lëtzebuergesch"},
    {"id":"lg","itemName":"Luganda","nativeName":"Luganda"},
    {"id":"li","itemName":"Limburgish, Limburgan, Limburger","nativeName":"Limburgs"},
    {"id":"ln","itemName":"Lingala","nativeName":"Lingála"},
    {"id":"lo","itemName":"Lao","nativeName":"ພາສາລາວ"},
    {"id":"lt","itemName":"Lithuanian","nativeName":"lietuvių kalba"},
    {"id":"lu","itemName":"Luba-Katanga","nativeName":""},
    {"id":"lv","itemName":"Latvian","nativeName":"latviešu valoda"},
    {"id":"gv","itemName":"Manx","nativeName":"Gaelg, Gailck"},
    {"id":"mk","itemName":"Macedonian","nativeName":"македонски јазик"},
    {"id":"mg","itemName":"Malagasy","nativeName":"Malagasy fiteny"},
    {"id":"ms","itemName":"Malay","nativeName":"bahasa Melayu, بهاس ملايو‎"},
    {"id":"ml","itemName":"Malayalam","nativeName":"മലയാളം"},
    {"id":"mt","itemName":"Maltese","nativeName":"Malti"},
    {"id":"mi","itemName":"Māori","nativeName":"te reo Māori"},
    {"id":"mr","itemName":"Marathi (Marāṭhī)","nativeName":"मराठी"},
    {"id":"mh","itemName":"Marshallese","nativeName":"Kajin M̧ajeļ"},
    {"id":"mn","itemName":"Mongolian","nativeName":"монгол"},
    {"id":"na","itemName":"Nauru","nativeName":"Ekakairũ Naoero"},
    {"id":"nv","itemName":"Navajo, Navaho","nativeName":"Diné bizaad, Dinékʼehǰí"},
    {"id":"nb","itemName":"Norwegian Bokmål","nativeName":"Norsk bokmål"},
    {"id":"nd","itemName":"North Ndebele","nativeName":"isiNdebele"},
    {"id":"ne","itemName":"Nepali","nativeName":"नेपाली"},
    {"id":"ng","itemName":"Ndonga","nativeName":"Owambo"},
    {"id":"nn","itemName":"Norwegian Nynorsk","nativeName":"Norsk nynorsk"},
    {"id":"no","itemName":"Norwegian","nativeName":"Norsk"},
    {"id":"ii","itemName":"Nuosu","nativeName":"ꆈꌠ꒿ Nuosuhxop"},
    {"id":"nr","itemName":"South Ndebele","nativeName":"isiNdebele"},
    {"id":"oc","itemName":"Occitan","nativeName":"Occitan"},
    {"id":"oj","itemName":"Ojibwe, Ojibwa","nativeName":"ᐊᓂᔑᓈᐯᒧᐎᓐ"},
    {"id":"cu","itemName":"Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic","nativeName":"ѩзыкъ словѣньскъ"},
    {"id":"om","itemName":"Oromo","nativeName":"Afaan Oromoo"},
    {"id":"or","itemName":"Oriya","nativeName":"ଓଡ଼ିଆ"},
    {"id":"os","itemName":"Ossetian, Ossetic","nativeName":"ирон æвзаг"},
    {"id":"pa","itemName":"Panjabi, Punjabi","nativeName":"ਪੰਜਾਬੀ, پنجابی‎"},
    {"id":"pi","itemName":"Pāli","nativeName":"पाऴि"},
    {"id":"fa","itemName":"Persian","nativeName":"فارسی"},
    {"id":"pl","itemName":"Polish","nativeName":"polski"},
    {"id":"ps","itemName":"Pashto, Pushto","nativeName":"پښتو"},
    {"id":"pt","itemName":"Portuguese","nativeName":"Português"},
    {"id":"qu","itemName":"Quechua","nativeName":"Runa Simi, Kichwa"},
    {"id":"rm","itemName":"Romansh","nativeName":"rumantsch grischun"},
    {"id":"rn","itemName":"Kirundi","nativeName":"kiRundi"},
    {"id":"ro","itemName":"Romanian, Moldavian, Moldovan","nativeName":"română"},
    {"id":"ru","itemName":"Russian","nativeName":"русский язык"},
    {"id":"sa","itemName":"Sanskrit (Saṁskṛta)","nativeName":"संस्कृतम्"},
    {"id":"sc","itemName":"Sardinian","nativeName":"sardu"},
    {"id":"sd","itemName":"Sindhi","nativeName":"सिन्धी, سنڌي، سندھی‎"},
    {"id":"se","itemName":"Northern Sami","nativeName":"Davvisámegiella"},
    {"id":"sm","itemName":"Samoan","nativeName":"gagana faa Samoa"},
    {"id":"sg","itemName":"Sango","nativeName":"yângâ tî sängö"},
    {"id":"sr","itemName":"Serbian","nativeName":"српски језик"},
    {"id":"gd","itemName":"Scottish Gaelic; Gaelic","nativeName":"Gàidhlig"},
    {"id":"sn","itemName":"Shona","nativeName":"chiShona"},
    {"id":"si","itemName":"Sinhala, Sinhalese","nativeName":"සිංහල"},
    {"id":"sk","itemName":"Slovak","nativeName":"slovenčina"},
    {"id":"sl","itemName":"Slovene","nativeName":"slovenščina"},
    {"id":"so","itemName":"Somali","nativeName":"Soomaaliga, af Soomaali"},
    {"id":"st","itemName":"Southern Sotho","nativeName":"Sesotho"},
    {"id":"es","itemName":"Spanish; Castilian","nativeName":"español, castellano"},
    {"id":"su","itemName":"Sundanese","nativeName":"Basa Sunda"},
    {"id":"sw","itemName":"Swahili","nativeName":"Kiswahili"},
    {"id":"ss","itemName":"Swati","nativeName":"SiSwati"},
    {"id":"sv","itemName":"Swedish","nativeName":"svenska"},
    {"id":"ta","itemName":"Tamil","nativeName":"தமிழ்"},
    {"id":"te","itemName":"Telugu","nativeName":"తెలుగు"},
    {"id":"tg","itemName":"Tajik","nativeName":"тоҷикӣ, toğikī, تاجیکی‎"},
    {"id":"th","itemName":"Thai","nativeName":"ไทย"},
    {"id":"ti","itemName":"Tigrinya","nativeName":"ትግርኛ"},
    {"id":"bo","itemName":"Tibetan Standard, Tibetan, Central","nativeName":"བོད་ཡིག"},
    {"id":"tk","itemName":"Turkmen","nativeName":"Türkmen, Түркмен"},
    {"id":"tl","itemName":"Tagalog","nativeName":"Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔"},
    {"id":"tn","itemName":"Tswana","nativeName":"Setswana"},
    {"id":"to","itemName":"Tonga (Tonga Islands)","nativeName":"faka Tonga"},
    {"id":"tr","itemName":"Turkish","nativeName":"Türkçe"},
    {"id":"ts","itemName":"Tsonga","nativeName":"Xitsonga"},
    {"id":"tt","itemName":"Tatar","nativeName":"татарча, tatarça, تاتارچا‎"},
    {"id":"tw","itemName":"Twi","nativeName":"Twi"},
    {"id":"ty","itemName":"Tahitian","nativeName":"Reo Tahiti"},
    {"id":"ug","itemName":"Uighur, Uyghur","nativeName":"Uyƣurqə, ئۇيغۇرچە‎"},
    {"id":"uk","itemName":"Ukrainian","nativeName":"українська"},
    {"id":"ur","itemName":"Urdu","nativeName":"اردو"},
    {"id":"uz","itemName":"Uzbek","nativeName":"zbek, Ўзбек, أۇزبېك‎"},
    {"id":"ve","itemName":"Venda","nativeName":"Tshivenḓa"},
    {"id":"vi","itemName":"Vietnamese","nativeName":"Tiếng Việt"},
    {"id":"vo","itemName":"Volapük","nativeName":"Volapük"},
    {"id":"wa","itemName":"Walloon","nativeName":"Walon"},
    {"id":"cy","itemName":"Welsh","nativeName":"Cymraeg"},
    {"id":"wo","itemName":"Wolof","nativeName":"Wollof"},
    {"id":"fy","itemName":"Western Frisian","nativeName":"Frysk"},
    {"id":"xh","itemName":"Xhosa","nativeName":"isiXhosa"},
    {"id":"yi","itemName":"Yiddish","nativeName":"ייִדיש"},
    {"id":"yo","itemName":"Yoruba","nativeName":"Yorùbá"},
    {"id":"za","itemName":"Zhuang, Chuang","nativeName":"Saɯ cueŋƅ, Saw cuengh"}
  ]
